const ADD_TO_CART = "ADD_TO_CART"
const REMOVE_GOODS_IN_CART = 'REMOVE_GOODS_IN_CART'
const CHANGE_GOODS_QTY = 'CHANGE_GOODS_QTY'

export {
    ADD_TO_CART,
    REMOVE_GOODS_IN_CART,
    CHANGE_GOODS_QTY
}